### ISSUE TITLE
Find package conflicts

### ISSUE THREAD

**Issue by Rem1L** [fabrahman/ReBART#10]
Hello, I'm trying to train the model on my device but I find this error:'The conflict is caused by:The user requested transformers==3.0.0 sentence-transformers 2.0.0 depends on transformers<5.0.0 and >=4.6.0' I wonder that if there is a solution to this.

**Comment by brcsomnath** [comment]
This is probably due to an update of the sentence-transformers package requiring an updated dependency. 

You can use `transformers==4.6.0` in the requirements.txt and try to run the scripts. However, this may lead to small discrepancies in the final scores.
