### ISSUE TITLE
Do I need to set `truncation=True` ?

### ISSUE THREAD

**Issue by linbeyoung** [fabrahman/ReBART#12]
I got this error several times and not sure if I need to set it True, and where to set?

' Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'only_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you may want to check this is the right behavior.'

**Comment by brcsomnath** [comment]
Thanks for bringing this up. It was just a warning in the earlier versions of Huggingface.

Yes, you can set truncation=True to resolve this issue.

**Comment by linbeyoung** [comment]
Well, I am not sure that if it influences the performance of the model theoretically?
