### ISSUE TITLE
Could not open dataset example

### ISSUE THREAD

**Issue by xinzehuang** [fabrahman/ReBART#2]
The link for
An example is provided for ROCStories in __here__.
is not available.
Could you please just paste it here?

**Comment by brcsomnath** [comment]
Thank you for pointing this out. We will fix the link. In the meantime you can refer to the example below:

`{"orig_sents": ["2", "0", "3", "4", "1"], "shuf_sents": ["Dan was overweight as well.", "They got themselves and dan on a diet.", "Dan 's parents were overweight.", "The doctors told his parents it was unhealthy.", "His parents understood and decided to make a change."]}`
