### ISSUE TITLE
question about decoder output

### ISSUE THREAD

**Issue by llllearner** [fabrahman/ReBART#5]
Why the decoder output of ReBART is some numbers(2, 0, 3, 1, 4, etc.), i think it would be better if change to <S2>, <S0>, etc., which is same with the input sentence order indexes format.
2, 0, 3, 1, 4, etc. should means numbers, not the target order indexes.

**Comment by llllearner** [comment]
or another question: Why you choose "**the decoder encapsulates the functioning of a pointer network while generating output sentence positions.**"

**Comment by brcsomnath** [comment]
In our experiments, we found that having the input and output format that we used in our paper yields the best results. 

In a pointer network, during decoding the output token is generated by attending over the input sequence. The decoder of the BART can be thought of as something similar, where while outputting a particular sentence index it attends over the encoder output and selects the respective one. Figure 6 in our paper illustrates this phenomenon.
