### ISSUE TITLE
Use saved model to predict sentence sequence "shuf_sents", but no "orig_sents".

### ISSUE THREAD

**Issue by faiz-hub** [fabrahman/ReBART#7]
**Dear fabrahman,**
Appreciate for your great work for ReBART.
I have a question here:
- Let say, we already done with training our model.
- Can we generate/predict order of the test data (shuffled sentence sequence) but with only "shuf_sents" column?, no "orig_sents" column
- Because, if we check on **load_data** function, it return examples (list of tupple) consist of shuf_sents and orif_sents

Thank you in advance,
**Faiz**

**Comment by brcsomnath** [comment]
Thank you for your interest in our work.

Yes you can generate the output without having the original sentences. Ideally you would not require the output during inference. The easiest way to achieve this is to have an empty list in the orig_sentences. You can do this by either modifying the load_data function or having the json such that the parsed set of sentences is empty. 

Let me know if you have any further questions.
