### ISSUE TITLE
Method to ensure decoding output contain all input sequences?

### ISSUE THREAD

**Issue by bryanzhou008** [fabrahman/ReBART#8]
Great work! Did you use any methods to enforce that the decoder outputs contained all the input sentences or did the model just learn that from the training data you provided? If yes, could you point me to the relevant code? I will cite your paper, thanks!

**Comment by brcsomnath** [comment]
We did not use any specific constraints to enforce the output. However, you can add constraints during training/inference such that the decoded output lie within the max number of sentences within an input.

**Comment by bryanzhou008** [comment]
I see, so am I understanding correctly that in your case the model learned from training data by it self to generate a reordering of all the markers while not generating any duplicates?

**Comment by brcsomnath** [comment]
Yes it worked perfectly for small inputs where the number of sentences were low (e.g. ROCDatasets), we did observe some degenerate output for larger inputs in some cases. We considered the accuracy and other metrics to be zero for those instances.

**Comment by bryanzhou008** [comment]
I see, thank you very much for your clarification!
