### ISSUE TITLE
Python environment

### ISSUE THREAD

**Issue by KoyuMizutani** [fabrahman/ReBART#9]
Hi,
I am interested in your research and tried to run your code, but there is a conflict in the environment setup.
Could you please tell me what version of python you are using?
Sincerely,

**Comment by brcsomnath** [comment]
Thank you for your interest in our work. 

We have updated the requirements.txt to resolve this issue [here](https://github.com/fabrahman/ReBART/commit/6a4fd6fe4f48d3b6c1c396c9a917a3bb1184825e). We tested the codebase on python version 3.8.11.

**Comment by KoyuMizutani** [comment]
Thank you for your support!
